
version: '3.8'
services:
  althenaserver:
    build:
      context: ./athenahealth_backend
    ports:
      - "3000:3000"
    container_name: althenaserver
 
  athenaui:
    build:
      context: ./athenahealth_ui
    ports:
      - "5173:5173"
    container_name: athenaui

  # cernerui:
  #   build:
  #     context: ./cerner_ui
  #   ports:
  #       - "8000:8000"
  #   container_name: cernerui
